version: "2"

linters:
  default: "none"
  enable:
    - govet
    - revive
    - bodyclose
    - misspell
    - nilerr
    - nilnil
    - sloglint
    - depguard
    - iface
    - unparam

  settings:
    sloglint:
      no-mixed-args: true
      kv-only: true
      no-global: all
      context: all
      static-msg: true
      msg-style: lowercased
      key-naming-case: snake

    revive:
      max-open-files: 2048
      rules:
        - name: bool-literal-in-expr
        - name: context-as-argument
          arguments:
            - allowTypesBefore: "*testing.T"
        - name: duplicated-imports
        - name: early-return
          arguments:
            - preserve-scope
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
          arguments:
            - preserve-scope
        - name: range
        - name: range-val-address
        - name: superfluous-else
          arguments:
            - preserve-scope
        - name: time-equal
        - name: unnecessary-stmt
        - name: unused-parameter
        - name: use-any

    # [source](https://sourcegraph.com/github.com/aquasecurity/trivy-db/-/blob/.golangci.yaml?L84-86)
    staticcheck:
      checks:
        - all
        - -QF1008 # Omit embedded fields from selector expression
        - -S1007  # Simplify regular expression by using raw string literal
        - -S1011  # Use a single append to concatenate two slices
        - -S1023  # Omit redundant control flow
        - -SA1019 # Using a deprecated function, variable, constant or field
        - -SA1024 # A string cutset contains duplicate characters
        - -SA4004 # The loop exits unconditionally after one iteration
        - -SA4023 # Impossible comparison of interface value with untyped nil
        - -SA4032 # Comparing runtime.GOOS or runtime.GOARCH against impossible value
        - -SA5011 # Possible nil pointer dereference
        - -ST1003 # Poorly chosen identifier
        - -ST1012 # Poorly chosen name for error variable

    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: reflect
          # allow:
          #   - $gostd
          #   - github.com/nxtcoder17
          #   - github.com/urfave/cli/v3

    iface:
      enable:
        - identical
